from __future__ import annotations

from app.db.session import Base
from app.models.messaging import (
    Announcement,
    AlertDelivery,
    Message,
    MessageAuditLog,
    MessageParticipant,
    MessageThread,
    ParentLink,
    SafetyAlert,
)
from app.models.merch import MerchDesign, MerchDesignLayer, MerchExport, MerchProduct, MerchTemplate, TeamMerchConfig
from app.models.recruiting import (
    RecruitingHighlight,
    RecruitingNote,
    RecruitingProfile,
    RecruitingTag,
    RecruitingVisibility,
    RecruitingWatchlist,
)
from app.models.schedule import Event, PracticeBlock, PracticePlan, PracticeTemplate, PracticeTemplateBlock
from app.models.store import (
    CartItem,
    Order,
    OrderItem,
    PaymentWebhookEvent,
    Product,
    ProductCategory,
    ProductImage,
    TeamStoreConfig,
    Vendor,
)
from app.models.stats import AthleteStatSnapshot, Match, MatchStats, StatAuditLog, TeamStatSnapshot
from app.models.team import Team, TeamMember
from app.models.tournament import (
    Bracket,
    BracketMatch,
    SavedTournament,
    SeedScore,
    SeedingOverride,
    Tournament,
    TournamentAlertSubscription,
    TournamentChangeLog,
    TournamentDualBout,
    TournamentDualMeet,
    TournamentDivision,
    TournamentEntry,
    TournamentExternal,
    TournamentFilter,
    TournamentMat,
    TournamentScanRun,
    TournamentSource,
    TournamentTeam,
)
from app.models.user import (
    AuthRateLimitEvent,
    EmailVerificationToken,
    PasswordResetToken,
    RefreshToken,
    User,
    UserPushDevice,
)
from app.models.weight import AthleteTarget, HydrationLog, WeightAlert, WeightLog, WeightPlan

__all__ = [
    "Base",
    "User",
    "UserPushDevice",
    "RefreshToken",
    "PasswordResetToken",
    "EmailVerificationToken",
    "AuthRateLimitEvent",
    "Team",
    "TeamMember",
    "Tournament",
    "TournamentDivision",
    "TournamentTeam",
    "TournamentMat",
    "TournamentDualMeet",
    "TournamentDualBout",
    "TournamentEntry",
    "TournamentSource",
    "TournamentExternal",
    "SavedTournament",
    "TournamentFilter",
    "TournamentScanRun",
    "TournamentChangeLog",
    "TournamentAlertSubscription",
    "SeedScore",
    "SeedingOverride",
    "Bracket",
    "BracketMatch",
    "MessageThread",
    "MessageParticipant",
    "Message",
    "Announcement",
    "AlertDelivery",
    "MessageAuditLog",
    "ParentLink",
    "SafetyAlert",
    "RecruitingProfile",
    "RecruitingVisibility",
    "RecruitingWatchlist",
    "RecruitingNote",
    "RecruitingTag",
    "RecruitingHighlight",
    "MerchProduct",
    "MerchDesign",
    "MerchDesignLayer",
    "MerchTemplate",
    "MerchExport",
    "TeamMerchConfig",
    "Event",
    "PracticePlan",
    "PracticeBlock",
    "PracticeTemplate",
    "PracticeTemplateBlock",
    "Vendor",
    "ProductCategory",
    "Product",
    "ProductImage",
    "TeamStoreConfig",
    "Order",
    "OrderItem",
    "CartItem",
    "PaymentWebhookEvent",
    "Match",
    "MatchStats",
    "AthleteStatSnapshot",
    "TeamStatSnapshot",
    "StatAuditLog",
    "WeightLog",
    "WeightPlan",
    "HydrationLog",
    "AthleteTarget",
    "WeightAlert",
]
