from __future__ import annotations
from typing import Optional

from app.models.messaging import Announcement, Message, MessageAuditLog, MessageParticipant, MessageThread, ParentLink
from app.models.merch import MerchDesign, MerchDesignLayer, MerchExport, MerchProduct, MerchTemplate, TeamMerchConfig
from app.models.recruiting import (
    RecruitingHighlight,
    RecruitingNote,
    RecruitingProfile,
    RecruitingTag,
    RecruitingVisibility,
    RecruitingWatchlist,
)
from app.models.schedule import Event, PracticeBlock, PracticePlan, PracticeTemplate, PracticeTemplateBlock
from app.models.store import (
    CartItem,
    Order,
    OrderItem,
    PaymentWebhookEvent,
    Product,
    ProductCategory,
    ProductImage,
    TeamStoreConfig,
    Vendor,
)
from app.models.stats import AthleteStatSnapshot, Match, MatchStats, StatAuditLog, TeamStatSnapshot
from app.models.team import Team, TeamMember
from app.models.tournament import (
    Bracket,
    BracketMatch,
    SavedTournament,
    SeedScore,
    SeedingOverride,
    Tournament,
    TournamentDivision,
    TournamentEntry,
    TournamentExternal,
    TournamentFilter,
    TournamentSource,
    TournamentTeam,
)
from app.models.user import EmailVerificationToken, PasswordResetToken, RefreshToken, User
from app.models.weight import AthleteTarget, HydrationLog, WeightAlert, WeightLog, WeightPlan

__all__ = [
    "User",
    "RefreshToken",
    "PasswordResetToken",
    "EmailVerificationToken",
    "Team",
    "TeamMember",
    "Tournament",
    "TournamentDivision",
    "TournamentTeam",
    "TournamentEntry",
    "TournamentSource",
    "TournamentExternal",
    "SavedTournament",
    "TournamentFilter",
    "SeedScore",
    "SeedingOverride",
    "Bracket",
    "BracketMatch",
    "MessageThread",
    "MessageParticipant",
    "Message",
    "Announcement",
    "MessageAuditLog",
    "ParentLink",
    "RecruitingProfile",
    "RecruitingVisibility",
    "RecruitingWatchlist",
    "RecruitingNote",
    "RecruitingTag",
    "RecruitingHighlight",
    "MerchProduct",
    "MerchDesign",
    "MerchDesignLayer",
    "MerchTemplate",
    "MerchExport",
    "TeamMerchConfig",
    "Event",
    "PracticePlan",
    "PracticeBlock",
    "PracticeTemplate",
    "PracticeTemplateBlock",
    "Vendor",
    "ProductCategory",
    "Product",
    "ProductImage",
    "TeamStoreConfig",
    "Order",
    "OrderItem",
    "CartItem",
    "PaymentWebhookEvent",
    "Match",
    "MatchStats",
    "AthleteStatSnapshot",
    "TeamStatSnapshot",
    "StatAuditLog",
    "WeightLog",
    "WeightPlan",
    "HydrationLog",
    "AthleteTarget",
    "WeightAlert",
]
